In [1]:
from re import VERBOSE
from tensorflow import keras
from tensorflow.keras.models import load_model
import numpy as np
import cv2

In [33]:
model_mnist = load_model('C://Users/nguye/Desktop/VanAn/SUDOKU/model/classifier_vgg16_project.h5')


In [35]:
img_input = cv2.imread("C://Users/nguye/Desktop/VanAn/SUDOKU/Reference/Sudoku_AI-master/CleanedBoardCells/cell12.png",0)
img_input2 = np.array(img_input)
img_input2.shape
img_input3 = cv2.resize(img_input2,(28,28))
img_input3 = img_input3.reshape(1,28,28,1)
img_input4 = img_input3/255.0
pred_result = model_mnist.predict(img_input4)

In [36]:
np.round(pred_result*100)

array([[ 0.,  0.,  0.,  0.,  0., 99.,  0.,  0.,  1.,  0.]], dtype=float32)

In [57]:
img_input = []
for i in range(1,13):
    img_read = cv2.imread("C://Users/nguye/Desktop/VanAn/SUDOKU/Image/number/img_test%d.jpeg"%i,0)
    img_input.append(img_read)
    print(img_read.shape)
img_input2 = np.array(img_input)
img_input2.shape
# cv2.imshow("before",img_input)

# print("img_input shape1: ", img_input.shape)
# print("img_input lenght1: ", len(img_input))

# cv2.waitKey(0)

(28, 28)
(28, 28)
(28, 28)
(28, 28)
(28, 28)
(28, 28)
(28, 28)
(28, 28)
(28, 28)
(28, 28)
(28, 28)
(28, 28)


(12, 28, 28)

In [58]:
img_input3 = img_input2.reshape(12,28,28,1)
# cv2.imshow("after",img_input3)
# cv2.waitKey(0)

In [60]:
img_input4 = img_input3 / 255.0
#img_input4 = img_input3 
img_input4.shape
cv2.imshow("input_4",img_input4[11])
cv2.waitKey(0)

-1

In [61]:
pred_result = model_mnist.predict(img_input4)
pred_result.shape

(12, 10)

In [63]:
pred_result[11]

array([1.0832676e-03, 5.0876463e-09, 2.3963125e-06, 2.4203191e-05,
       5.1682888e-05, 1.4192060e-01, 8.5250348e-01, 5.1610482e-07,
       1.4684089e-03, 2.9453724e-03], dtype=float32)

In [64]:
a = pred_result.argmax(axis=1)

In [65]:
a

array([9, 9, 2, 7, 3, 5, 6, 9, 4, 5, 9, 6], dtype=int64)

In [49]:
img_test = cv2.imread("C://Users/nguye/Desktop/VanAn/SUDOKU/Image/test/6.png")

In [50]:
img_test = cv2.cvtColor(img_test,cv2.COLOR_BGR2GRAY)
img_test = cv2.resize(img_test,(28,28))

In [51]:
img_test = cv2.bitwise_not(img_test,img_test)

In [52]:
cv2.imshow("img_test2",img_test)
cv2.waitKey(0)

-1

In [55]:
cv2.imwrite("C://Users/nguye/Desktop/VanAn/SUDOKU/Image/test/img1_6.jpeg",img_test)

True

In [ ]:
import gzip
content = "Lots of content here"
f = gzip.open('Onlyfinnaly.log.gz', 'wb')
f.write(content)
f.close()